import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export function exportWorkoutPDF(workout, weightUnit = "kg") {
    const doc = new jsPDF();

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("LiftLog", 20, 20);

    doc.setFontSize(18);
    doc.text("Workout Summary", 20, 30);

    doc.setDrawColor(220);
    doc.line(20, 35, 190, 35);

    // Workout info
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    let y = 45;

    doc.text(`Workout: ${workout.name}`, 20, y);
    y += 8;

    doc.text(`Category: ${workout.category || "-"}`, 20, y);
    y += 8;

    doc.text(`Goal: ${workout.goal || "-"}`, 20, y);
    y += 8;

    doc.text(`Difficulty: ${workout.difficulty || "-"}`, 20, y);
    y += 8;

    if (workout.summary) {
        doc.text(`Duration: ${workout.summary.duration}`, 20, y);
        y += 8;

        doc.text(`Calories Burned: ${workout.summary.calories}`, 20, y);
        y += 8;

        doc.text(
            `Total Volume: ${Number(workout.summary.volume).toLocaleString()} ${weightUnit}`,
            20,
            y
        );
        y += 8;

        doc.text(
            `Exercises Completed: ${workout.summary.completedExercises}/${workout.summary.totalExercises}`,
            20,
            y
        );
        y += 8;

        doc.text(
            `Completed: ${new Date(workout.summary.loggedDate).toLocaleString()}`,
            20,
            y
        );
    }

    // Exercise table
    autoTable(doc, {
        startY: y + 10,
        head: [["Exercise", "Sets", "Reps", `Weight (${weightUnit})`, "Completed"]],
        body: workout.exercises.map(ex => [
            ex.name,
            ex.sets || "-",
            ex.reps || "-",
            ex.weight || "-",
            ex.completed ? "✓" : ""
        ]),
        theme: "striped",
        headStyles: {
            fillColor: [37, 99, 235]
        }
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
        "Generated by LiftLog",
        20,
        pageHeight - 15
    );

    doc.save(`${workout.name}.pdf`);
}